// 27 AdVista Originals built via the compact factory. Each entry stays
// fully editable — Fabric.js JSON, variable contract, layout DNA and
// AI metadata are all produced from the config.
import { makeTemplate, type TemplateConfig } from "./factory";
import type { OriginalTemplateModule } from "../templateBuilder";

const CONFIGS: TemplateConfig[] = [
  // Beauty +1
  { slug: "velvet-lip-drop", name: "Velvet Lip Drop", description: "Bold beauty drop announcement with saturated color block and typographic hero.", category: "Beauty", collection_slug: "beauty", platform: "Instagram", objective: "Awareness", format: "square", ai_tags: ["bold","color-block","launch"], industry_tags: ["Beauty","Cosmetics"], emotion: "Confident", audience: "Women 18-30", layout_style: "Typographic", visual_style: "Bold", bg: "#2A0F1E", accent: "#F04E7B", ink: "#FFF3F7", headline: "The Velvet Drop", subheadline: "New Season · Limited Edition", body: "12 saturated shades. One perfect blur finish.", cta: "Shop the Drop", headline_font: "Playfair Display", style: "editorial" },

  // Fashion 3
  { slug: "runway-noir", name: "Runway Noir", description: "Editorial fashion cover with oversized serif headline and portrait hero.", category: "Fashion", collection_slug: "fashion", platform: "Instagram", objective: "Awareness", format: "portrait", ai_tags: ["editorial","noir","runway"], industry_tags: ["Fashion","Apparel"], emotion: "Aspirational", audience: "Women 25-40", layout_style: "Editorial", visual_style: "Minimal", bg: "#0B0B0B", accent: "#D4B27A", ink: "#F5F1EA", headline: "Runway. Refined.", subheadline: "AW26 Collection", body: "Timeless silhouettes cut for the modern wardrobe.", cta: "Explore Collection", headline_font: "Playfair Display", style: "editorial" },
  { slug: "streetwear-drop", name: "Streetwear Drop", description: "Streetwear launch template with grunge accent and left-aligned copy.", category: "Fashion", collection_slug: "fashion", platform: "Instagram", objective: "Conversions", format: "square", ai_tags: ["streetwear","urban","drop"], industry_tags: ["Fashion","Streetwear"], emotion: "Energetic", audience: "Gen Z", layout_style: "Asymmetric", visual_style: "Bold", bg: "#111111", accent: "#F2FF2E", ink: "#FFFFFF", headline: "Drop 07 / Now Live", subheadline: "Limited Run", body: "Only 300 pieces. Ships worldwide.", cta: "Cop Now", text_alignment: "left", hero_position: "right", style: "bold" },
  { slug: "capsule-linen", name: "Capsule Linen", description: "Soft neutral capsule collection template for premium apparel brands.", category: "Fashion", collection_slug: "fashion", platform: "Instagram", objective: "Traffic", format: "portrait", ai_tags: ["minimal","premium","capsule"], industry_tags: ["Fashion","Sustainable"], emotion: "Calm", audience: "Adults 30-45", layout_style: "Minimal", visual_style: "Minimal", bg: "#EFE7DA", accent: "#8C6A4F", ink: "#3B2A1F", headline: "The Linen Capsule", subheadline: "Slow Fashion · Summer 26", body: "Nine essentials. Built to last a decade.", cta: "Discover", headline_font: "Playfair Display", style: "minimal" },

  // Real Estate 2
  { slug: "urban-loft-listing", name: "Urban Loft Listing", description: "Modern property listing template with large hero and address block.", category: "Real Estate", collection_slug: "real-estate", platform: "Facebook", objective: "Traffic", format: "portrait", ai_tags: ["listing","modern","property"], industry_tags: ["Real Estate"], emotion: "Aspirational", audience: "Buyers 30-55", layout_style: "Product Focus", visual_style: "Modern", bg: "#F4F1EC", accent: "#0F3A5F", ink: "#0F1A24", headline: "Loft 402 · Brooklyn", subheadline: "Just Listed", body: "2 bed · 2 bath · 1,450 sqft · Roof deck.", cta: "Book Tour", style: "corporate" },
  { slug: "open-house-sunday", name: "Open House Sunday", description: "Bold open-house event template with weekend accent color.", category: "Real Estate", collection_slug: "real-estate", platform: "Instagram", objective: "Engagement", format: "square", ai_tags: ["event","open house","weekend"], industry_tags: ["Real Estate"], emotion: "Urgent", audience: "Local buyers", layout_style: "Announcement", visual_style: "Bold", bg: "#0F3A5F", accent: "#F2C14E", ink: "#FFFFFF", headline: "Open House Sunday", subheadline: "1pm — 4pm", body: "128 Maple Ave · Refreshments provided.", cta: "RSVP", style: "bold" },

  // Restaurant & Food 2
  { slug: "chef-special-friday", name: "Chef's Special Friday", description: "Warm restaurant special of the day template with menu tone.", category: "Restaurant & Food", collection_slug: "restaurant-food", platform: "Instagram", objective: "Engagement", format: "square", ai_tags: ["menu","special","warm"], industry_tags: ["Restaurant","Food"], emotion: "Warm", audience: "Local diners", layout_style: "Editorial", visual_style: "Warm", bg: "#2B1810", accent: "#E88B4B", ink: "#F8ECD9", headline: "Chef's Special", subheadline: "Friday Only", body: "Slow-braised short rib with truffle pommes purée.", cta: "Reserve a Table", headline_font: "Playfair Display", style: "editorial" },
  { slug: "delivery-deal", name: "Delivery Deal", description: "High-contrast delivery promo with bold discount call-out.", category: "Restaurant & Food", collection_slug: "restaurant-food", platform: "Facebook", objective: "Conversions", format: "square", ai_tags: ["promo","discount","delivery"], industry_tags: ["Restaurant","QSR"], emotion: "Playful", audience: "Families", visual_style: "Playful", layout_style: "Promo", bg: "#FFE93D", accent: "#D0021B", ink: "#1A1A1A", headline: "20% Off Delivery", subheadline: "This Weekend", body: "Use code TASTY20 at checkout.", cta: "Order Now", style: "playful" },

  // Fitness +1
  { slug: "morning-hiit", name: "Morning HIIT", description: "Energetic HIIT class promo template for boutique studios.", category: "Fitness", collection_slug: "fitness", platform: "Instagram", objective: "Traffic", format: "portrait", ai_tags: ["hiit","boutique","energy"], industry_tags: ["Fitness","Studio"], emotion: "Energetic", audience: "Adults 20-35", layout_style: "Bold Type", visual_style: "Bold", bg: "#0A0A0A", accent: "#FF3B3B", ink: "#FFFFFF", headline: "Morning HIIT", subheadline: "6am · Every Weekday", body: "40 minutes. Every muscle. Zero excuses.", cta: "Book a Class", style: "bold" },

  // SaaS & Technology +1
  { slug: "product-hunt-launch", name: "Product Hunt Launch", description: "Clean SaaS launch template optimized for LinkedIn and X.", category: "SaaS & Technology", collection_slug: "saas-technology", platform: "LinkedIn", objective: "Awareness", format: "landscape", ai_tags: ["launch","saas","clean"], industry_tags: ["SaaS","Startup"], emotion: "Excited", audience: "Founders / PMs", layout_style: "Split", visual_style: "Modern", bg: "#0B1220", accent: "#7C5CFF", ink: "#F5F7FF", headline: "We just launched.", subheadline: "Live on Product Hunt", body: "Give us an upvote and shape what ships next.", cta: "Support the Launch", text_alignment: "left", hero_position: "right", style: "minimal" },

  // Healthcare 2
  { slug: "clinic-checkup", name: "Clinic Checkup", description: "Trustworthy healthcare template with calm palette and CTA.", category: "Healthcare", collection_slug: "healthcare", platform: "Facebook", objective: "Traffic", format: "square", ai_tags: ["clinic","trust","checkup"], industry_tags: ["Healthcare","Clinic"], emotion: "Calm", audience: "Adults 30-60", layout_style: "Announcement", visual_style: "Clean", bg: "#EAF4F4", accent: "#2E8B8B", ink: "#0D3B3B", headline: "Annual Checkup Season", subheadline: "Book by month end", body: "Comprehensive exams covered by most insurers.", cta: "Book Appointment", style: "corporate" },
  { slug: "dental-smile", name: "Dental Smile", description: "Friendly dental promotion template with soft pastel accents.", category: "Healthcare", collection_slug: "healthcare", platform: "Instagram", objective: "Conversions", format: "portrait", ai_tags: ["dental","smile","friendly"], industry_tags: ["Healthcare","Dental"], emotion: "Friendly", audience: "Families", layout_style: "Product Focus", visual_style: "Playful", bg: "#F4F1FF", accent: "#7C5CFF", ink: "#251A5A", headline: "A Brighter Smile", subheadline: "New Patient Special", body: "$99 cleaning + exam for first visits this month.", cta: "Claim Offer", style: "playful" },

  // Education 2
  { slug: "enrollment-open", name: "Enrollment Open", description: "Bold enrollment template for online courses and cohorts.", category: "Education", collection_slug: "education", platform: "Instagram", objective: "Conversions", format: "square", ai_tags: ["cohort","enrollment","learning"], industry_tags: ["Education","EdTech"], emotion: "Motivated", audience: "Learners 18-40", layout_style: "Bold Type", visual_style: "Bold", bg: "#1A0F3E", accent: "#F2C14E", ink: "#FFFFFF", headline: "Cohort 12 · Now Open", subheadline: "Starts March 1", body: "12 weeks, live mentors, real projects.", cta: "Apply Today", style: "bold" },
  { slug: "webinar-invite", name: "Webinar Invite", description: "Clean webinar invite template with speaker slot and date block.", category: "Education", collection_slug: "education", platform: "LinkedIn", objective: "Engagement", format: "landscape", ai_tags: ["webinar","invite","professional"], industry_tags: ["Education","B2B"], emotion: "Professional", audience: "Professionals", layout_style: "Split", visual_style: "Modern", bg: "#FFFFFF", accent: "#0F62FE", ink: "#0B1220", headline: "Free Live Webinar", subheadline: "Thursday · 2pm ET", body: "How top teams ship 3x more experiments per quarter.", cta: "Save My Seat", text_alignment: "left", hero_position: "right", style: "minimal" },

  // Automotive 2
  { slug: "test-drive-event", name: "Test Drive Event", description: "Automotive weekend test drive event with dark cinematic look.", category: "Automotive", collection_slug: "automotive", platform: "Facebook", objective: "Traffic", format: "landscape", ai_tags: ["test drive","event","cinematic"], industry_tags: ["Automotive","Dealer"], emotion: "Aspirational", audience: "Adults 25-55", layout_style: "Cinematic", visual_style: "Bold", bg: "#0A0A0A", accent: "#E10600", ink: "#FFFFFF", headline: "Test Drive Weekend", subheadline: "Sat & Sun · All Models", body: "Reserve your slot and drive home with the keys.", cta: "Reserve a Slot", text_alignment: "left", hero_position: "right", style: "bold" },
  { slug: "ev-launch", name: "EV Launch", description: "Premium electric vehicle reveal template with futuristic gradient feel.", category: "Automotive", collection_slug: "automotive", platform: "Instagram", objective: "Awareness", format: "portrait", ai_tags: ["ev","launch","premium"], industry_tags: ["Automotive","EV"], emotion: "Innovative", audience: "Early adopters", layout_style: "Hero", visual_style: "Modern", bg: "#0B1220", accent: "#3EE0C6", ink: "#F5F7FF", headline: "The Next Mile", subheadline: "All-Electric · 2026", body: "410-mile range. Zero compromises.", cta: "Reserve Now", style: "minimal" },

  // Finance 2
  { slug: "invest-smarter", name: "Invest Smarter", description: "Fintech app promo template with credible dark palette.", category: "Finance", collection_slug: "finance", platform: "LinkedIn", objective: "Conversions", format: "square", ai_tags: ["fintech","invest","app"], industry_tags: ["Finance","Fintech"], emotion: "Confident", audience: "Adults 25-45", layout_style: "Split", visual_style: "Modern", bg: "#0B1220", accent: "#3EC97C", ink: "#F5F7FF", headline: "Invest Smarter", subheadline: "Zero-fee trades", body: "Automate your portfolio in under two minutes.", cta: "Download App", style: "corporate" },
  { slug: "tax-season", name: "Tax Season", description: "Timely tax filing service template with urgency and clarity.", category: "Finance", collection_slug: "finance", platform: "Facebook", objective: "Traffic", format: "portrait", ai_tags: ["tax","urgent","service"], industry_tags: ["Finance","Accounting"], emotion: "Urgent", audience: "Adults 25-60", layout_style: "Announcement", visual_style: "Clean", bg: "#F5F7FA", accent: "#0F62FE", ink: "#0B1220", headline: "Tax Season is Here", subheadline: "File in under 20 minutes", body: "Certified experts, average $312 refund boost.", cta: "Start Filing", style: "corporate" },

  // Travel 2
  { slug: "island-getaway", name: "Island Getaway", description: "Vacation package template with warm tropical palette.", category: "Travel", collection_slug: "travel", platform: "Instagram", objective: "Conversions", format: "portrait", ai_tags: ["tropical","getaway","package"], industry_tags: ["Travel","Hospitality"], emotion: "Escapist", audience: "Adults 25-55", layout_style: "Hero", visual_style: "Warm", bg: "#0E4C5C", accent: "#F2C14E", ink: "#FFF9EC", headline: "Island Getaway", subheadline: "From $899 · All-inclusive", body: "7 nights, oceanfront villa, breakfast included.", cta: "Book Now", headline_font: "Playfair Display", style: "editorial" },
  { slug: "city-break", name: "City Break", description: "Weekend city break template with vibrant tour operator vibe.", category: "Travel", collection_slug: "travel", platform: "Facebook", objective: "Traffic", format: "square", ai_tags: ["city","weekend","tour"], industry_tags: ["Travel","Tour"], emotion: "Excited", audience: "Millennials", layout_style: "Split", visual_style: "Bold", bg: "#F4F1EC", accent: "#E85D4C", ink: "#2B1810", headline: "Weekend in Lisbon", subheadline: "3 nights from $429", body: "Boutique hotels, curated tours, zero hassle.", cta: "See Deal", style: "bold" },

  // E-commerce 2
  { slug: "flash-sale-48h", name: "Flash Sale 48H", description: "Urgent flash sale template with countdown-ready copy slot.", category: "E-commerce", collection_slug: "ecommerce", platform: "Instagram", objective: "Conversions", format: "square", ai_tags: ["flash sale","urgent","discount"], industry_tags: ["E-commerce","DTC"], emotion: "Urgent", audience: "Shoppers", layout_style: "Promo", visual_style: "Bold", bg: "#FF2E63", accent: "#111111", ink: "#FFFFFF", cta_ink: "#FF2E63", headline: "48 Hours · 40% Off", subheadline: "Site-wide Flash Sale", body: "Every category. Every collection. Ends Sunday.", cta: "Shop the Sale", style: "bold" },
  { slug: "new-arrivals", name: "New Arrivals", description: "Clean new arrivals template ideal for weekly product drops.", category: "E-commerce", collection_slug: "ecommerce", platform: "Instagram", objective: "Traffic", format: "portrait", ai_tags: ["new arrivals","drop","weekly"], industry_tags: ["E-commerce","DTC"], emotion: "Fresh", audience: "Shoppers 20-40", layout_style: "Product Focus", visual_style: "Minimal", bg: "#F7F5F1", accent: "#2A2A2A", ink: "#111111", headline: "New This Week", subheadline: "12 fresh drops", body: "Curated by our design team. Free shipping over $75.", cta: "Shop New", style: "minimal" },

  // Agency 2
  { slug: "case-study-hero", name: "Case Study Hero", description: "Agency case study spotlight template for LinkedIn.", category: "Agency", collection_slug: "agency", platform: "LinkedIn", objective: "Awareness", format: "landscape", ai_tags: ["case study","agency","b2b"], industry_tags: ["Agency","B2B"], emotion: "Confident", audience: "Marketers", layout_style: "Split", visual_style: "Corporate", bg: "#0B1220", accent: "#7C5CFF", ink: "#F5F7FF", headline: "3.4x ROAS in 90 Days", subheadline: "Case Study · DTC Skincare", body: "How we scaled paid social without burning creative.", cta: "Read the Story", text_alignment: "left", hero_position: "right", style: "corporate" },
  { slug: "we-are-hiring", name: "We're Hiring", description: "Warm recruiting template for agencies and studios.", category: "Agency", collection_slug: "agency", platform: "Instagram", objective: "Engagement", format: "square", ai_tags: ["hiring","recruiting","warm"], industry_tags: ["Agency","Studio"], emotion: "Welcoming", audience: "Job seekers", layout_style: "Announcement", visual_style: "Warm", bg: "#FFF1E6", accent: "#E85D4C", ink: "#2B1810", headline: "We're Hiring", subheadline: "Senior Brand Designer · Remote", body: "Come build category-defining brands with us.", cta: "See the Role", style: "playful" },

  // Seasonal 2
  { slug: "black-friday-bold", name: "Black Friday Bold", description: "High-impact Black Friday template with maximal typography.", category: "Seasonal", collection_slug: "seasonal", platform: "Instagram", objective: "Conversions", format: "square", ai_tags: ["black friday","seasonal","bold"], industry_tags: ["Retail","Seasonal"], emotion: "Urgent", audience: "Shoppers", layout_style: "Bold Type", visual_style: "Bold", bg: "#000000", accent: "#F2FF2E", ink: "#FFFFFF", cta_ink: "#000000", headline: "Black Friday · 50% Off", subheadline: "One day only", body: "Every product. Every size. Free shipping over $50.", cta: "Shop Now", style: "bold" },
  { slug: "holiday-warmth", name: "Holiday Warmth", description: "Cozy holiday season template with festive palette.", category: "Seasonal", collection_slug: "seasonal", platform: "Instagram", objective: "Engagement", format: "portrait", ai_tags: ["holiday","cozy","festive"], industry_tags: ["Retail","Seasonal"], emotion: "Warm", audience: "Families", layout_style: "Editorial", visual_style: "Warm", bg: "#2B0A0A", accent: "#E8B84B", ink: "#FFF3D9", headline: "Warm Wishes", subheadline: "Holiday Collection", body: "Handmade gifts, ready to unwrap.", cta: "Shop Gifts", headline_font: "Playfair Display", style: "editorial" },

  // Business 1
  { slug: "quarterly-update", name: "Quarterly Update", description: "Professional quarterly update template for B2B leaders.", category: "Business", collection_slug: "business", platform: "LinkedIn", objective: "Engagement", format: "landscape", ai_tags: ["b2b","quarterly","leadership"], industry_tags: ["Business","B2B"], emotion: "Confident", audience: "Executives", layout_style: "Split", visual_style: "Corporate", bg: "#F5F7FA", accent: "#0F62FE", ink: "#0B1220", headline: "Q3 in Review", subheadline: "Growth · Milestones · What's next", body: "A quick recap for our partners, customers, and team.", cta: "Read the Recap", text_alignment: "left", hero_position: "right", style: "corporate" },
];

export const BULK_ORIGINALS: OriginalTemplateModule[] = CONFIGS.map(makeTemplate);
