// AITemplateGeneratorService — the single entry point for AI-generated templates.
// Pages never call the edge function directly; they call `generate(ctx)` here.
// Pipeline: AI Context -> Blueprint -> (Edge Function: copy + image strategy)
// -> Renderer -> editable Fabric.js JSON -> TemplateRecord handoff.

import { supabase } from "@/integrations/supabase/client";
import type { BrandIdentity } from "@/services/ai/BrandService";
import type { TemplateRecord, FabricTemplateJSON } from "@/services/templates/types";
import { TemplateBlueprintService, type TemplateBlueprint } from "./TemplateBlueprintService";
import { TemplateRenderingService } from "./TemplateRenderingService";
import { MarketingCopyService, type GeneratedCopy } from "./MarketingCopyService";
import { TemplateLearningService } from "./TemplateLearningService";

export interface GenerateTemplateInput {
  brand?: BrandIdentity | null;
  category?: string | null;
  goal?: string | null;
  platform?: string | null;
  productName?: string | null;
  targetAudience?: string | null;
  campaignId?: string | null;
  userId?: string | null;
  // Optional user prompt to bias copy generation.
  prompt?: string | null;
}

export interface GeneratedTemplate {
  template: TemplateRecord;
  blueprint: TemplateBlueprint;
  copy: GeneratedCopy;
  reasoning: string[];
  confidence: number;
}

export const AITemplateGeneratorService = {
  async generate(input: GenerateTemplateInput): Promise<GeneratedTemplate> {
    const blueprint = TemplateBlueprintService.build({
      brand: input.brand,
      category: input.category,
      goal: input.goal,
      platform: input.platform,
      productName: input.productName,
      targetAudience: input.targetAudience,
      campaignId: input.campaignId,
    });

    // Ask the edge function to generate copy + pick a hero image URL.
    let copy: GeneratedCopy = MarketingCopyService.fallback(blueprint);
    let heroImageUrl: string | undefined;
    let reasoning: string[] = [];
    let confidence = 0.6;

    try {
      const { data, error } = await supabase.functions.invoke("generate-ai-template", {
        body: { blueprint, prompt: input.prompt ?? null },
      });
      if (!error && data?.success) {
        if (data.copy) copy = { ...copy, ...data.copy };
        heroImageUrl = data.heroImageUrl ?? undefined;
        reasoning = Array.isArray(data.reasoning) ? data.reasoning : reasoning;
        if (typeof data.confidence === "number") confidence = data.confidence;
      }
    } catch (err) {
      console.warn("[AITemplateGeneratorService] edge function failed, using fallback", err);
    }

    const json: FabricTemplateJSON = TemplateRenderingService.render(blueprint, copy, heroImageUrl);
    const now = new Date().toISOString();
    const name = `AI • ${input.productName ?? blueprint.context.category ?? "Creative"}`;

    const template: TemplateRecord = {
      id: `ai-${crypto.randomUUID()}`,
      name,
      description: `Generated by AdVista AI for ${blueprint.context.category ?? "your brand"}.`,
      category: blueprint.context.category,
      platform: blueprint.context.platform,
      objective: blueprint.context.goal,
      format: `${blueprint.layout.aspect.width}x${blueprint.layout.aspect.height}`,
      width: blueprint.layout.aspect.width,
      height: blueprint.layout.aspect.height,
      preview_url: null,
      thumbnail_url: null,
      template_json: json,
      ai_tags: [blueprint.layout.layout, blueprint.style.imageStrategy, blueprint.layout.cta_style],
      industry_tags: blueprint.context.category ? [blueprint.context.category] : [],
      brand_compatible: true,
      popularity_score: 0,
      source: "ai_generated",
      premium: false,
      metadata: {
        layout_style: blueprint.layout.layout,
        primary_color: blueprint.style.palette.primary,
        recommended_platforms: blueprint.context.platform ? [blueprint.context.platform] : [],
        recommended_goal: blueprint.context.goal ? [blueprint.context.goal] : [],
      },
      created_by: input.userId ?? null,
      created_at: now,
      updated_at: now,
    };

    if (input.userId) {
      TemplateLearningService.record({
        userId: input.userId,
        blueprint,
        templateId: template.id,
        outcome: "generated",
      });
    }

    return { template, blueprint, copy, reasoning, confidence };
  },
};
