import { useMemo } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import {
  ArrowLeft, Download, LayoutGrid, Sparkles, Wand2, Layers, Palette, Type,
  Image as ImageIcon, Info,
} from 'lucide-react';

import { supabase } from '@/integrations/supabase/client';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Separator } from '@/components/ui/separator';
import { toast } from '@/hooks/use-toast';
import { downloadTemplate } from '@/services/templates/templateDownload';
import { setPendingEditorTemplate } from '@/lib/templateEditorSession';
import type { TemplateRecord, FabricObjectJSON } from '@/services/templates/types';
import type { OriginalTemplate } from '@/hooks/useOriginalsSearch';

/* ---------- Variable placeholder registry ---------- */
const VARIABLE_DOCS: Array<{
  key: string;
  label: string;
  description: string;
  owner: 'Brand' | 'AI' | 'User';
  example: string;
}> = [
  { key: 'brand.logo', label: 'Brand logo', description: 'Filled from the active Brand Kit logo URL.', owner: 'Brand', example: 'https://cdn.brand/logo.png' },
  { key: 'brand.primaryColor', label: 'Primary color', description: 'Primary hex color from the Brand Kit.', owner: 'Brand', example: '#8B5CF6' },
  { key: 'brand.secondaryColor', label: 'Secondary color', description: 'Secondary hex color from the Brand Kit.', owner: 'Brand', example: '#FFC107' },
  { key: 'brand.font', label: 'Brand font', description: 'Primary typography family from the Brand Kit.', owner: 'Brand', example: 'Poppins' },
  { key: 'brand.voice', label: 'Brand voice', description: 'Tone descriptor used by the AI Copywriter.', owner: 'Brand', example: 'Confident, warm' },
  { key: 'headline', label: 'Headline', description: 'Primary attention line generated by the AI Copywriter.', owner: 'AI', example: 'Summer, reimagined.' },
  { key: 'subheadline', label: 'Subheadline', description: 'Supporting line under the headline.', owner: 'AI', example: 'Up to 50% off new arrivals.' },
  { key: 'body', label: 'Body copy', description: 'Longer descriptive block for storytelling formats.', owner: 'AI', example: 'A fresh drop for every mood…' },
  { key: 'cta', label: 'Call to action', description: 'Short action verb pushed to the CTA button.', owner: 'AI', example: 'Shop now' },
  { key: 'offer', label: 'Offer / promo', description: 'Discount or promotion string, if applicable.', owner: 'AI', example: '50% off' },
  { key: 'website', label: 'Website', description: 'Brand website URL surfaced on the creative.', owner: 'User', example: 'advista.com' },
  { key: 'phone', label: 'Phone', description: 'Contact phone number for lead formats.', owner: 'User', example: '+1 555 000 1234' },
  { key: 'product_image', label: 'Product image', description: 'Featured product photo used in product-focused layouts.', owner: 'User', example: 'https://cdn/product.png' },
  { key: 'hero_image', label: 'Hero image', description: 'Full-bleed background or lifestyle photo.', owner: 'User', example: 'https://cdn/hero.png' },
];

const OWNER_STYLE: Record<'Brand' | 'AI' | 'User', string> = {
  Brand: 'bg-purple-500/10 text-purple-600 border-purple-500/20',
  AI: 'bg-primary/10 text-primary border-primary/20',
  User: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20',
};

/* ---------- Walk JSON to detect which placeholders the template actually declares ---------- */
const collectDeclaredKeys = (objects: FabricObjectJSON[] | undefined, out = new Set<string>()): Set<string> => {
  if (!Array.isArray(objects)) return out;
  const PATTERN = /\{\{\s*([a-zA-Z0-9_.-]+)\s*\}\}/g;
  for (const obj of objects) {
    if (obj?.variableKey) out.add(String(obj.variableKey));
    for (const field of ['text', 'src'] as const) {
      const v = obj?.[field];
      if (typeof v === 'string') {
        let m;
        while ((m = PATTERN.exec(v)) !== null) out.add(m[1]);
      }
    }
    const children = (obj as { objects?: FabricObjectJSON[] }).objects;
    if (children) collectDeclaredKeys(children, out);
  }
  return out;
};

/* ---------- Data hook ---------- */
const useOriginalTemplate = (id?: string) =>
  useQuery<OriginalTemplate | null, Error>({
    queryKey: ['original-template', id],
    enabled: !!id,
    queryFn: async () => {
      const { data, error } = await supabase.from('templates').select('*').eq('id', id!).maybeSingle();
      if (error) throw error;
      return (data ?? null) as OriginalTemplate | null;
    },
  });

/* ---------- Page ---------- */
const OriginalTemplateDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { data: t, isLoading } = useOriginalTemplate(id);

  const declaredKeys = useMemo(
    () => collectDeclaredKeys(t?.template_json?.objects),
    [t?.template_json],
  );

  const layerCount = t?.template_json?.objects?.length ?? 0;

  const handleUse = () => {
    if (!t) return;
    setPendingEditorTemplate(t as unknown as TemplateRecord, 'originals');
    toast({
      title: 'Template loaded into editor',
      description: 'AI, brand and copy placeholders will be resolved on open.',
    });
    navigate('/visual-editor');
  };

  const handleExport = () => {
    if (!t) return;
    downloadTemplate({
      id: t.id,
      name: t.name,
      description: t.description,
      category: t.category,
      platform: t.platform,
      objective: t.objective,
      template_json: t.template_json ?? null,
      metadata: t.metadata,
      layout_dna: t.layout_dna ?? t.metadata,
      ai_tags: t.ai_tags ?? undefined,
      industry_tags: t.industry_tags ?? undefined,
      brand_compatible: t.brand_compatible ?? undefined,
    });
  };

  if (isLoading) {
    return (
      <div className="page-container py-8 space-y-6">
        <Skeleton className="h-8 w-64" />
        <div className="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
          <Skeleton className="aspect-[4/5] rounded-2xl" />
          <Skeleton className="h-96 rounded-2xl" />
        </div>
      </div>
    );
  }

  if (!t) {
    return (
      <div className="page-container py-16 text-center space-y-3">
        <LayoutGrid className="mx-auto h-10 w-10 text-muted-foreground" />
        <p className="font-semibold">Template not found</p>
        <Button variant="outline" onClick={() => navigate('/originals')}>Back to Originals</Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="page-container space-y-6 py-4 sm:py-6 lg:py-8">
        {/* Breadcrumb / back */}
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={() => navigate('/originals')} className="gap-1.5">
            <ArrowLeft className="h-4 w-4" /> Originals
          </Button>
          <span className="text-muted-foreground">/</span>
          <span className="text-sm font-medium truncate">{t.name}</span>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
          {/* Rendered preview */}
          <div className="space-y-3">
            <Card className="overflow-hidden rounded-2xl border-border/60">
              <div className="aspect-[4/5] w-full bg-muted">
                {t.preview_url || t.thumbnail_url ? (
                  <img
                    src={t.preview_url ?? t.thumbnail_url ?? ''}
                    alt={t.name}
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <div className="flex h-full w-full items-center justify-center bg-gradient-to-br from-primary/20 to-primary/5">
                    <LayoutGrid className="h-12 w-12 text-primary/40" />
                  </div>
                )}
              </div>
            </Card>

            <div className="flex flex-wrap gap-2">
              <Button onClick={handleUse} className="gap-2">
                <Wand2 className="h-4 w-4" /> Use this template
              </Button>
              <Button variant="outline" onClick={handleExport} className="gap-2">
                <Download className="h-4 w-4" /> Export JSON
              </Button>
              <Button
                variant="ghost"
                onClick={() => navigate('/template-customizer', { state: { templateData: t } })}
                className="gap-2"
              >
                <Sparkles className="h-4 w-4" /> Quick customize
              </Button>
            </div>
          </div>

          {/* Metadata */}
          <div className="space-y-4">
            <div>
              <Badge className="mb-2 gap-1 rounded-full bg-primary/10 text-primary hover:bg-primary/15">
                <Sparkles className="h-3 w-3" /> AdVista Original
              </Badge>
              <h1 className="text-2xl font-bold tracking-tight lg:text-3xl">{t.name}</h1>
              {t.description && (
                <p className="mt-1 text-sm text-muted-foreground">{t.description}</p>
              )}
            </div>

            <Card className="rounded-2xl">
              <CardContent className="grid grid-cols-2 gap-4 p-4 text-sm">
                <Meta icon={LayoutGrid} label="Category" value={t.category} />
                <Meta icon={ImageIcon} label="Platform" value={t.platform} />
                <Meta icon={Sparkles} label="Goal" value={t.objective} />
                <Meta icon={Palette} label="Emotion" value={t.metadata?.emotion} />
                <Meta icon={Layers} label="Layout" value={t.metadata?.layout_style ?? t.layout_dna?.layout_style} />
                <Meta icon={Type} label="Audience" value={t.metadata?.audience} />
              </CardContent>
            </Card>

            {(t.industry_tags?.length ?? 0) > 0 && (
              <TagBlock label="Industry" tags={t.industry_tags ?? []} variant="secondary" />
            )}
            {(t.ai_tags?.length ?? 0) > 0 && (
              <TagBlock label="AI tags" tags={t.ai_tags ?? []} variant="outline" />
            )}

            <Card className="rounded-2xl">
              <CardContent className="grid grid-cols-3 gap-4 p-4 text-center">
                <Stat label="Layers" value={layerCount} />
                <Stat label="Placeholders" value={declaredKeys.size} />
                <Stat label="Brand-ready" value={t.brand_compatible ? 'Yes' : 'No'} />
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Placeholder documentation */}
        <section>
          <div className="mb-3 flex items-center gap-2">
            <Info className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Variable placeholders</h2>
            <Badge variant="secondary" className="rounded-full text-[10px]">
              {declaredKeys.size} used in this template
            </Badge>
          </div>
          <p className="mb-3 max-w-3xl text-sm text-muted-foreground">
            Placeholders are resolved by the Template Engine at open-time. Brand values fill from your active Brand Kit,
            AI values from the Copywriter, and user values from the editor form.
          </p>

          <Card className="rounded-2xl">
            <CardContent className="p-0">
              <div className="divide-y">
                {VARIABLE_DOCS.map((v) => {
                  const used = declaredKeys.has(v.key);
                  return (
                    <div
                      key={v.key}
                      className={`grid gap-3 p-4 sm:grid-cols-[minmax(0,220px)_minmax(0,1fr)_auto] sm:items-center ${
                        used ? '' : 'opacity-60'
                      }`}
                    >
                      <div className="flex flex-col gap-1">
                        <code className="w-fit rounded-md bg-muted px-1.5 py-0.5 font-mono text-[11px]">
                          {'{{'}
                          {v.key}
                          {'}}'}
                        </code>
                        <span className="text-xs font-semibold">{v.label}</span>
                      </div>
                      <div className="min-w-0">
                        <p className="text-xs text-muted-foreground">{v.description}</p>
                        <p className="mt-1 truncate text-[11px] font-mono text-muted-foreground/80">
                          e.g. {v.example}
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline" className={`rounded-full text-[10px] ${OWNER_STYLE[v.owner]}`}>
                          {v.owner}
                        </Badge>
                        <Badge
                          variant={used ? 'default' : 'outline'}
                          className="rounded-full text-[10px]"
                        >
                          {used ? 'In use' : 'Optional'}
                        </Badge>
                      </div>
                    </div>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        </section>

        <Separator />

        <div className="flex flex-wrap items-center justify-between gap-3 pb-4">
          <p className="text-xs text-muted-foreground">
            Template ID <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[10px]">{t.id}</code>
          </p>
          <Button onClick={handleUse} className="gap-2">
            <Wand2 className="h-4 w-4" /> Use this template
          </Button>
        </div>
      </div>
    </div>
  );
};

const Meta = ({ icon: Icon, label, value }: { icon: any; label: string; value?: string | null }) =>
  value ? (
    <div className="flex items-start gap-2">
      <Icon className="mt-0.5 h-3.5 w-3.5 text-muted-foreground" />
      <div>
        <p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p>
        <p className="font-medium">{value}</p>
      </div>
    </div>
  ) : null;

const TagBlock = ({ label, tags, variant }: { label: string; tags: string[]; variant: 'outline' | 'secondary' }) => (
  <div>
    <p className="mb-1.5 text-xs font-semibold text-muted-foreground">{label}</p>
    <div className="flex flex-wrap gap-1">
      {tags.map((t) => (
        <Badge key={t} variant={variant} className="text-[10px]">
          {t}
        </Badge>
      ))}
    </div>
  </div>
);

const Stat = ({ label, value }: { label: string; value: string | number }) => (
  <div>
    <p className="text-lg font-bold">{value}</p>
    <p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p>
  </div>
);

export default OriginalTemplateDetail;
