// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nseqinedckubsypjjcpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZXFpbmVkY2t1YnN5cGpqY3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTA0MzIsImV4cCI6MjA2OTcyNjQzMn0.NUG6HcgBlwoq7FNmZp4M1WhnJYjejBPSFLyrspxXpBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});